### ISSUE TITLE
error when using a long list of msu locusID

### ISSUE THREAD

**Issue by htnani** [TomHarrop/oryzr#12]
Hi,

I'm getting this error when I try to use the LocToGeneName function with a long list of msu locus ID.
Here the code I'm using:
library(oryzr)
Id <- agtrf %>% select("Gene_ID")
Id = as.character(Id)
GeneName = LocToGeneName(Id)

![selection_044](https://user-images.githubusercontent.com/37335092/48802674-2fae1e80-ed10-11e8-93c8-adc672d3fa8e.png)

Please how can I fix this?

**Comment by TomHarrop** [comment]
Hi,

Thanks for letting me know about this. Could you please provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), or maybe just provide the list of MSU IDs?

You could use `dput(Id)` and copy the resulting structure into a comment inside code blocks.

I'm sure we can work out what is going wrong!

Thanks,
Tom

**Comment by htnani** [comment]
Hi Tom,

Here the requested. 
`dput(Id)`
`"c(\"LOC_Os01g01600\", \"LOC_Os01g04020\", \"LOC_Os01g04930\", \"LOC_Os01g06640\", \"LOC_Os01g07120\", \"LOC_Os01g07120\", \"LOC_Os01g08710\", \"LOC_Os01g09100\", \"LOC_Os01g09850\", \"LOC_Os01g09850\", \"LOC_Os01g09900\", \"LOC_Os01g09930\", \"LOC_Os01g11350\", \"LOC_Os01g11910\", \"LOC_Os01g13740\", \"LOC_Os01g14720\", \"LOC_Os01g15350\", \"LOC_Os01g15640\", \"LOC_Os01g16810\", \"LOC_Os01g18240\", \"LOC_Os01g18584\", \"LOC_Os01g19050\", \"LOC_Os01g19330\", \"LOC_Os01g24070\", \"LOC_Os01g24070\", \"LOC_Os01g29840\", \"LOC_Os01g36220\", \"LOC_Os01g40260\", \n\"LOC_Os01g40430\", \"LOC_Os01g41900\", \"LOC_Os01g44430\", \"LOC_Os01g47560\", \"LOC_Os01g48060\", \"LOC_Os01g48320\", \"LOC_Os01g48446\", \"LOC_Os01g48700\", \"LOC_Os01g49160\", \"LOC_Os01g50110\", \"LOC_Os01g51690\", \"LOC_Os01g52410\", \"LOC_Os01g52514\", \"LOC_Os01g53040\", \"LOC_Os01g55750\", \"LOC_Os01g56690\", \"LOC_Os01g59660\", \"LOC_Os01g60020\", \"LOC_Os01g60600\", \"LOC_Os01g61080\", \"LOC_Os01g62190\", \"LOC_Os01g62410\", \"LOC_Os01g62460\", \"LOC_Os01g62460\", \"LOC_Os01g63460\", \"LOC_Os01g64000\", \"LOC_Os01g64310\", \"LOC_Os01g64790\", \n\"LOC_Os01g65080\", \"LOC_Os01g65080\", \"LOC_Os01g66030\", \"LOC_Os01g66590\", \"LOC_Os01g66590\", \"LOC_Os01g67480\", \"LOC_Os01g68370\", \"LOC_Os01g68700\", \"LOC_Os01g70230\", \"LOC_Os01g70270\", \"LOC_Os01g71970\", \"LOC_Os01g72370\", \"LOC_Os01g72370\", \"LOC_Os01g74020\", \"LOC_Os01g74410\", \"LOC_Os02g01355\", \"LOC_Os02g01365\", \"LOC_Os02g02370\", \"LOC_Os02g02424\", \"LOC_Os02g02480\", \"LOC_Os02g06370\", \"LOC_Os02g07170\", \"LOC_Os02g07800\", \"LOC_Os02g08544\", \"LOC_Os02g08544\", \"LOC_Os02g09830\", \"LOC_Os02g10860\", \"LOC_Os02g12790\", \n\"LOC_Os02g14910\", \"LOC_Os02g15340\", \"LOC_Os02g15350\", \"LOC_Os02g16240\", \"LOC_Os02g16680\", \"LOC_Os02g16680\", \"LOC_Os02g18460\", \"LOC_Os02g19804\", \"LOC_Os02g25470\", \"LOC_Os02g26780\", \"LOC_Os02g29550\", \"LOC_Os02g29550\", \"LOC_Os02g32140\", \"LOC_Os02g36360\", \"LOC_Os02g36890\", \"LOC_Os02g36924\", \"LOC_Os02g39220\", \"LOC_Os02g39360\", \"LOC_Os02g39710\", \"LOC_Os02g40070\", \"LOC_Os02g40950\", \"LOC_Os02g41510\", \"LOC_Os02g43790\", \"LOC_Os02g45420\", \"LOC_Os02g47060\", \"LOC_Os02g47280\", \"LOC_Os02g47744\", \"LOC_Os02g49410\", \n\"LOC_Os02g49700\", \"LOC_Os02g49700\", \"LOC_Os02g50630\", \"LOC_Os02g51799\", \"LOC_Os02g52340\", \"LOC_Os02g52670\", \"LOC_Os02g52780\", \"LOC_Os02g54160\", \"LOC_Os02g54160\", \"LOC_Os02g55250\", \"LOC_Os02g55320\", \"LOC_Os02g55380\", \"LOC_Os02g56600\", \"LOC_Os03g02160\", \"LOC_Os03g02240\", \"LOC_Os03g03164\", \"LOC_Os03g05510\", \"LOC_Os03g06930\", \"LOC_Os03g07450\", \"LOC_Os03g07880\", \"LOC_Os03g07880\", \"LOC_Os03g08500\", \"LOC_Os03g08620\", \"LOC_Os03g08754\", \"LOC_Os03g08930\", \"LOC_Os03g09100\", \"LOC_Os03g09280\", \"LOC_Os03g10140\", \n\"LOC_Os03g10210\", \"LOC_Os03g11614\", \"LOC_Os03g12350\", \"LOC_Os03g12370\", \"LOC_Os03g12760\", \"LOC_Os03g12860\", \"LOC_Os03g15680\", \"LOC_Os03g17810\", \"LOC_Os03g19120\", \"LOC_Os03g20310\", \"LOC_Os03g20900\", \"LOC_Os03g20910\", \"LOC_Os03g21060\", \"LOC_Os03g21710\", \"LOC_Os03g25120\", \"LOC_Os03g32220\", \"LOC_Os03g32230\", \"LOC_Os03g38210\", \"LOC_Os03g40160\", \"LOC_Os03g41330\", \"LOC_Os03g42100\", \"LOC_Os03g43840\", \"LOC_Os03g47740\", \"LOC_Os03g50310\", \"LOC_Os03g50920\", \"LOC_Os03g51710\", \"LOC_Os03g52239\", \"LOC_Os03g55220\", \n\"LOC_Os03g55220\", \"LOC_Os03g55540\", \"LOC_Os03g55590\", \"LOC_Os03g58160\", \"LOC_Os03g60560\", \"LOC_Os03g60570\", \"LOC_Os03g62379\", \"LOC_Os04g23910\", \"LOC_Os04g25100\", \"LOC_Os04g28580\", \"LOC_Os04g31730\", \"LOC_Os04g31804\", \"LOC_Os04g32590\", \"LOC_Os04g32790\", \"LOC_Os04g34970\", \"LOC_Os04g35010\", \"LOC_Os04g35250\", \"LOC_Os04g39470\", \"LOC_Os04g41820\", \"LOC_Os04g42020\", \"LOC_Os04g42570\", \"LOC_Os04g43560\", \"LOC_Os04g45020\", \"LOC_Os04g45330\", \"LOC_Os04g45940\", \"LOC_Os04g46020\", \"LOC_Os04g46580\", \"LOC_Os04g47750\", \n\"LOC_Os04g47860\", \"LOC_Os04g48510\", \"LOC_Os04g49380\", \"LOC_Os04g50770\", \"LOC_Os04g51190\", \"LOC_Os04g51190\", \"LOC_Os04g52090\", \"LOC_Os04g52410\", \"LOC_Os04g52810\", \"LOC_Os04g53540\", \"LOC_Os04g53540\", \"LOC_Os04g53990\", \"LOC_Os04g54880\", \"LOC_Os04g54900\", \"LOC_Os04g55970\", \"LOC_Os04g56170\", \"LOC_Os04g58190\", \"LOC_Os05g03740\", \"LOC_Os05g03800\", \"LOC_Os05g04210\", \"LOC_Os05g04640\", \"LOC_Os05g07120\", \"LOC_Os05g07120\", \"LOC_Os05g07270\", \"LOC_Os05g09020\", \"LOC_Os05g09020\", \"LOC_Os05g11510\", \"LOC_Os05g14370\", \n\"LOC_Os05g27930\", \"LOC_Os05g27930\", \"LOC_Os05g27930\", \"LOC_Os05g28320\", \"LOC_Os05g28350\", \"LOC_Os05g34310\", \"LOC_Os05g34450\", \"LOC_Os05g34830\", \"LOC_Os05g34940\", \"LOC_Os05g34940\", \"LOC_Os05g34940\", \"LOC_Os05g37050\", \"LOC_Os05g37540\", \"LOC_Os05g39790\", \"LOC_Os05g40960\", \"LOC_Os05g41166\", \"LOC_Os05g41450\", \"LOC_Os05g43920\", \"LOC_Os05g45410\", \"LOC_Os05g48820\", \"LOC_Os05g49280\", \"LOC_Os05g50340\", \"LOC_Os05g50700\", \"LOC_Os05g51830\", \"LOC_Os06g01670\", \"LOC_Os06g02230\", \"LOC_Os06g03710\", \"LOC_Os06g04090\", \n\"LOC_Os06g05380\", \"LOC_Os06g07030\", \"LOC_Os06g08500\", \"LOC_Os06g09370\", \"LOC_Os06g09370\", \"LOC_Os06g09420\", \"LOC_Os06g10350\", \"LOC_Os06g10880\", \"LOC_Os06g10880\", \"LOC_Os06g10880\", \"LOC_Os06g12210\", \"LOC_Os06g14190\", \"LOC_Os06g15330\", \"LOC_Os06g17410\", \"LOC_Os06g19444\", \"LOC_Os06g29020\", \"LOC_Os06g30090\", \"LOC_Os06g32860\", \"LOC_Os06g32860\", \"LOC_Os06g35900\", \"LOC_Os06g36000\", \"LOC_Os06g37450\", \"LOC_Os06g39090\", \"LOC_Os06g39960\", \"LOC_Os06g40960\", \"LOC_Os06g41770\", \"LOC_Os06g43090\", \"LOC_Os06g44010\", \n\"LOC_Os06g44860\", \"LOC_Os06g45650\", \"LOC_Os06g45890\", \"LOC_Os06g46270\", \"LOC_Os06g49010\", \"LOC_Os06g50600\", \"LOC_Os06g51260\", \"LOC_Os07g01180\", \"LOC_Os07g02060\", \"LOC_Os07g03770\", \"LOC_Os07g04700\", \"LOC_Os07g08420\", \"LOC_Os07g09590\", \"LOC_Os07g12340\", \"LOC_Os07g17230\", \"LOC_Os07g22730\", \"LOC_Os07g22770\", \"LOC_Os07g25150\", \"LOC_Os07g25710\", \"LOC_Os07g38090\", \"LOC_Os07g38090\", \"LOC_Os07g39320\", \"LOC_Os07g39470\", \"LOC_Os07g40000\", \"LOC_Os07g42510\", \"LOC_Os07g44690\", \"LOC_Os07g44950\", \"LOC_Os07g48596\", \n\"LOC_Os07g48660\", \"LOC_Os07g48820\", \"LOC_Os07g48820\", \"LOC_Os08g02300\", \"LOC_Os08g04190\", \"LOC_Os08g05520\", \"LOC_Os08g06110\", \"LOC_Os08g06110\", \"LOC_Os08g06110\", \"LOC_Os08g06120\", \"LOC_Os08g07970\", \"LOC_Os08g10560\", \"LOC_Os08g14400\", \"LOC_Os08g14880\", \"LOC_Os08g19590\", \"LOC_Os08g20486\", \"LOC_Os08g33670\", \"LOC_Os08g36700\", \"LOC_Os08g36790\", \"LOC_Os08g38990\", \"LOC_Os08g39830\", \"LOC_Os08g39890\", \"LOC_Os08g42400\", \"LOC_Os08g43334\", \"LOC_Os08g43550\", \"LOC_Os08g44820\", \"LOC_Os09g01140\", \"LOC_Os09g02780\", \n\"LOC_Os09g09630\", \"LOC_Os09g10840\", \"LOC_Os09g10980\", \"LOC_Os09g11480\", \"LOC_Os09g21180\", \"LOC_Os09g26170\", \"LOC_Os09g28200\", \"LOC_Os09g28210\", \"LOC_Os09g28310\", \"LOC_Os09g28354\", \"LOC_Os09g28440\", \"LOC_Os09g29360\", \"LOC_Os09g29960\", \"LOC_Os09g30400\", \"LOC_Os09g31140\", \"LOC_Os09g31390\", \"LOC_Os09g32040\", \"LOC_Os09g32260\", \"LOC_Os09g32948\", \"LOC_Os09g35030\", \"LOC_Os09g35790\", \"LOC_Os09g39490\", \"LOC_Os09g39660\", \"LOC_Os09g39850\", \"LOC_Os10g01470\", \"LOC_Os10g07080\", \"LOC_Os10g18099\", \"LOC_Os10g22430\", \n\"LOC_Os10g25220\", \"LOC_Os10g27360\", \"LOC_Os10g28340\", \"LOC_Os10g33760\", \"LOC_Os10g34884\", \"LOC_Os10g35300\", \"LOC_Os10g35300\", \"LOC_Os10g39130\", \"LOC_Os10g39130\", \"LOC_Os10g39750\", \"LOC_Os10g41460\", \"LOC_Os11g01480\", \"LOC_Os11g01550\", \"LOC_Os11g02530\", \"LOC_Os11g03110\", \"LOC_Os11g03300\", \"LOC_Os11g03420\", \"LOC_Os11g03440\", \"LOC_Os11g04960\", \"LOC_Os11g05340\", \"LOC_Os11g06020\", \"LOC_Os11g06170\", \"LOC_Os11g06170\", \"LOC_Os11g06410\", \"LOC_Os11g06770\", \"LOC_Os11g06770\", \"LOC_Os11g08210\", \"LOC_Os11g13930\", \n\"LOC_Os11g29870\", \"LOC_Os11g35390\", \"LOC_Os11g39000\", \"LOC_Os11g39000\", \"LOC_Os11g45850\", \"LOC_Os11g45950\", \"LOC_Os11g47460\", \"LOC_Os11g47630\", \"LOC_Os11g47870\", \"LOC_Os12g01490\", \"LOC_Os12g01550\", \"LOC_Os12g02440\", \"LOC_Os12g02450\", \"LOC_Os12g03050\", \"LOC_Os12g03150\", \"LOC_Os12g06200\", \"LOC_Os12g07640\", \"LOC_Os12g21850\", \"LOC_Os12g29330\", \"LOC_Os12g29520\", \"LOC_Os12g29520\", \"LOC_Os12g29520\", \"LOC_Os12g32140\", \"LOC_Os12g32400\", \"LOC_Os12g38960\", \"LOC_Os12g39400\", \"LOC_Os12g39640\", \"LOC_Os12g39990\", \n\"LOC_Os12g41230\", \"LOC_Os12g41680\", \"LOC_Os12g41860\", \"LOC_Os12g43950\", \"LOC_Os01g04750\", \"LOC_Os01g09620\", \"LOC_Os01g10580\", \"LOC_Os01g34060\", \"LOC_Os01g51154\", \"LOC_Os01g64730\", \"LOC_Os02g47190\", \"LOC_Os02g47660\", \"LOC_Os03g18340\", \"LOC_Os03g38870\", \"LOC_Os03g43810\", \"LOC_Os03g45450\", \"LOC_Os04g38720\", \"LOC_Os04g39960\", \"LOC_Os05g06340\", \"LOC_Os05g11414\", \"LOC_Os05g40080\", \"LOC_Os05g47650\", \"LOC_Os06g13670\", \"LOC_Os06g16370\", \"LOC_Os06g16400\", \"LOC_Os06g16400\", \"LOC_Os06g20020\", \"LOC_Os06g24070\", \n\"LOC_Os07g06620\", \"LOC_Os07g06620\", \"LOC_Os07g13170\", \"LOC_Os07g27670\", \"LOC_Os07g43530\", \"LOC_Os08g04840\", \"LOC_Os08g09800\", \"LOC_Os08g25820\", \"LOC_Os08g32440\", \"LOC_Os08g32990\", \"LOC_Os09g11480\", \"LOC_Os09g39660\", \"LOC_Os10g37240\", \"LOC_Os11g05640\", \"LOC_Os11g45740\", \"LOC_Os12g01180\", \"LOC_Os12g41060\", \"LOC_Os01g01870\", \"LOC_Os01g04020\", \"LOC_Os01g12860\", \"LOC_Os01g13740\", \"LOC_Os01g15900\", \"LOC_Os01g19970\", \"LOC_Os01g40670\", \"LOC_Os01g43230\", \"LOC_Os01g43650\", \"LOC_Os01g45090\", \"LOC_Os01g46870\", \n\"LOC_Os01g51140\", \"LOC_Os01g54990\", \"LOC_Os01g58760\", \"LOC_Os01g63510\", \"LOC_Os01g64360\", \"LOC_Os01g67770\", \"LOC_Os01g69850\", \"LOC_Os02g02424\", \"LOC_Os02g08150\", \"LOC_Os02g31160\", \"LOC_Os02g43820\", \"LOC_Os02g47280\", \"LOC_Os02g49480\", \"LOC_Os02g49880\", \"LOC_Os03g05500\", \"LOC_Os03g05590\", \"LOC_Os03g06860\", \"LOC_Os03g40080\", \"LOC_Os03g45750\", \"LOC_Os03g46860\", \"LOC_Os03g47740\", \"LOC_Os03g47740\", \"LOC_Os03g51580\", \"LOC_Os04g02510\", \"LOC_Os04g08290\", \"LOC_Os04g30870\", \"LOC_Os04g39570\", \"LOC_Os04g45750\", \n\"LOC_Os04g46400\", \"LOC_Os04g56850\", \"LOC_Os05g27980\", \"LOC_Os05g30720\", \"LOC_Os05g33810\", \"LOC_Os05g36100\", \"LOC_Os05g37060\", \"LOC_Os05g37190\", \"LOC_Os05g40070\", \"LOC_Os05g50310\", \"LOC_Os06g02560\", \"LOC_Os06g39906\", \"LOC_Os06g40710\", \"LOC_Os06g43910\", \"LOC_Os06g47590\", \"LOC_Os06g49010\", \"LOC_Os06g49010\", \"LOC_Os06g49880\", \"LOC_Os07g38030\", \"LOC_Os07g39800\", \"LOC_Os07g48560\", \"LOC_Os08g06240\", \"LOC_Os08g09810\", \"LOC_Os08g09840\", \"LOC_Os08g10080\", \"LOC_Os08g13840\", \"LOC_Os08g14880\", \"LOC_Os08g23470\", \n\"LOC_Os08g28214\", \"LOC_Os08g33150\", \"LOC_Os08g33660\", \"LOC_Os08g37810\", \"LOC_Os08g37920\", \"LOC_Os08g44830\", \"LOC_Os09g25070\", \"LOC_Os10g11580\", \"LOC_Os10g42130\", \"LOC_Os10g42160\", \"LOC_Os11g19060\", \"LOC_Os11g32100\", \"LOC_Os11g47620\", \"LOC_Os12g03110\", \"LOC_Os12g06640\", \"LOC_Os12g13570\", \"LOC_Os12g37690\", \"LOC_Os12g37970\", \"LOC_Os12g41950\", \"LOC_Os01g03720\", \"LOC_Os01g13460\", \"LOC_Os01g13520\", \"LOC_Os01g14440\", \"LOC_Os01g18850\", \"LOC_Os01g39330\", \"LOC_Os01g43550\", \"LOC_Os01g46800\", \"LOC_Os01g58420\", \n\"LOC_Os01g65900\", \"LOC_Os01g66120\", \"LOC_Os01g66270\", \"LOC_Os01g67970\", \"LOC_Os01g70270\", \"LOC_Os01g74540\", \"LOC_Os02g04680\", \"LOC_Os02g08440\", \"LOC_Os02g08540\", \"LOC_Os02g12820\", \"LOC_Os02g13710\", \"LOC_Os02g16540\", \"LOC_Os02g22020\", \"LOC_Os02g33560\", \"LOC_Os02g34520\", \"LOC_Os02g45200\", \"LOC_Os02g45450\", \"LOC_Os02g46030\", \"LOC_Os02g49230\", \"LOC_Os02g51280\", \"LOC_Os02g53690\", \"LOC_Os02g56250\", \"LOC_Os03g03760\", \"LOC_Os03g07360\", \"LOC_Os03g08960\", \"LOC_Os03g12370\", \"LOC_Os03g15660\", \"LOC_Os03g17150\", \n\"LOC_Os03g20090\", \"LOC_Os03g20310\", \"LOC_Os03g22170\", \"LOC_Os03g27390\", \"LOC_Os03g38610\", \"LOC_Os03g42630\", \"LOC_Os03g53050\", \"LOC_Os03g62230\", \"LOC_Os03g63810\", \"LOC_Os04g01480\", \"LOC_Os04g21950\", \"LOC_Os04g33950\", \"LOC_Os04g46350\", \"LOC_Os04g46440\", \"LOC_Os04g47860\", \"LOC_Os04g49230\", \"LOC_Os04g49450\", \"LOC_Os04g51190\", \"LOC_Os04g51320\", \"LOC_Os04g51560\", \"LOC_Os04g55520\", \"LOC_Os05g02390\", \"LOC_Os05g03550\", \"LOC_Os05g03860\", \"LOC_Os05g10620\", \"LOC_Os05g10670\", \"LOC_Os05g27730\", \"LOC_Os05g34730\", \n\"LOC_Os05g39720\", \"LOC_Os05g40280\", \"LOC_Os05g41760\", \"LOC_Os05g41780\", \"LOC_Os05g46020\", \"LOC_Os05g48010\", \"LOC_Os05g49620\", \"LOC_Os05g50350\", \"LOC_Os06g03670\", \"LOC_Os06g06360\", \"LOC_Os06g09370\", \"LOC_Os06g11860\", \"LOC_Os06g35140\", \"LOC_Os06g51070\", \"LOC_Os07g05010\", \"LOC_Os07g12510\", \"LOC_Os07g43580\", \"LOC_Os07g44640\", \"LOC_Os07g48180\", \"LOC_Os07g48870\", \"LOC_Os08g06140\", \"LOC_Os08g29660\", \"LOC_Os08g36220\", \"LOC_Os08g39390\", \"LOC_Os08g42400\", \"LOC_Os08g42400\", \"LOC_Os08g43160\", \"LOC_Os09g31400\", \n\"LOC_Os09g33580\", \"LOC_Os09g35010\", \"LOC_Os09g38570\", \"LOC_Os10g26620\", \"LOC_Os10g41200\", \"LOC_Os10g41230\", \"LOC_Os11g02470\", \"LOC_Os11g05614\", \"LOC_Os11g32110\", \"LOC_Os11g47910\", \"LOC_Os12g10630\", \"LOC_Os12g40570\", \"LOC_Os12g41920\", \"LOC_Os12g43790\", \"LOC_Os12g43950\", \"LOC_Os01g59780\", \"LOC_Os02g32590\", \"LOC_Os03g04070\", \"LOC_Os03g09170\")"`

Thanks a lot,

Hedia

**Comment by TomHarrop** [comment]
Hi Hedia,

That's not a character vector, it's a long string.

This works:

```r
> my_ids <- c("LOC_Os01g01600", "LOC_Os01g04020", "LOC_Os03g09170")
> LocToGeneName(my_ids)
            MsuID        RapID symbols                        names
1: LOC_Os01g01600 Os01g0105700    <NA>                         <NA>
2: LOC_Os01g04020 Os01g0131600  ERF108 ETHYLENE RESPONSE FACTOR 108
3: LOC_Os03g09170 Os03g0191900   ERF47  ETHYLENE RESPONSE FACTOR 47
                                                   MsuAnnotation OgroObjective
1:      ethylene-responsive protein related, putative, expressed          <NA>
2:                      AP2 domain containing protein, expressed          <NA>
3: ethylene-responsive transcription factor, putative, expressed          <NA>
   OgroRef
1:    <NA>
2:    <NA>
3:    <NA>
```

Whereas in your example, the long string is treated as a single MSU ID:

```r
> my_ids <- "c(\"LOC_Os01g01600\", \"LOC_Os01g04020\", \"LOC_Os03g09170\")"
> LocToGeneName(my_ids)
                                                     MsuID RapID symbols names
1: c("LOC_Os01g01600", "LOC_Os01g04020", "LOC_Os03g09170")  <NA>    <NA>  <NA>
   MsuAnnotation OgroObjective OgroRef
1:          <NA>          <NA>    <NA>
```
Hope this helps
Tom

**Comment by htnani** [comment]
Hi Tom,

It works. Sorry for the mistake.

Thanks a lot.

Hedia

**Comment by TomHarrop** [comment]
No problem, happy to help
